### ISSUE TITLE
Feature Request: Wallbox berücksichtigen

### ISSUE THREAD

**Issue by AlphaZuluNRW** [Zendure/Zendure-HA#410]
Ich habe heute ein "Problem" festgestellt. Die Integration reagiert schneller als meine Wallbox beim Überschussladen. Das führt dann dazu:

- Die Wallbox nimmt alles an Strom, was gerade eingespeist wird (bis zum Maximum, was Auto bzw. Box können).
- Kommt weniger Strom vom Dach schaltet die Box zurück und bei nur noch 1,4 kW ab.
- Die KEBA-Box (SolarEdge) ist aber recht träge, schaltet also erst zurück, wenn schon ein paar Sekunden Strom aus dem Netz kommt.
- Die Zendure-Integration sieht aber, dass da Netzstrom gezogen wird und speist ein.
- Das wiederum bekommt die Wallbox mit und schaltet nicht zurück.
- Nach und nach geht die dann auf das Maximum der Zendure-Einspeisung und leert die Akkus, was ja nicht der Sinn des Überschussladens ist.

Ich stelle mir das so vor, dass man der Integration auch einen Sensor nennen kann, der den Wallbox-Verbrauch "kennt", analog zur Einspeisung/Netzbezug. Wenn dort dann zu sehen ist, dass Strom ins Auto fließt, soll aus den Zendure-Speichern nichts eingespeist werden.

Ließe sich das einrichten? Oder kann man irgendwie über eine Automation das auch so machen?!?

Also: Wenn Auto lädt, dann Zendure Pause

**Comment by uremmel420** [comment]
Ich würde das zunächst mit einen Template Sensor versuchen, der [ Stromzähler Leistung - Wallbox Leistung ] berechnet und damit den Zendure ansteuern wie bisher. Damit wird die Wallbox bei der Zendure Regelung ignoriert.

Etwas so: 

```
template:
  - sensor:
    - name: "Zendure Stromzähler (ohne Wallbox)"
      unique_id: "zendure_stromzaehler_ohne_wallbox"
      device_class: power
      state_class: measurement
      unit_of_measurement: "W"
      state: >
        {% set sz = states('sensor.stromzaehler_leistung') | float(0) %}  # Stromzähler
        {% set wb = states('sensor.wallbox_leistung') | float(0) %}       # Wallbox
        {{ (sz - wb) }}
```

Ein Problem könnten hierbei die unterschiedlichen Aktualisierungszeiten der beiden Sensoren sein.
Testen kann ich das leider nicht.


Wenn deine PV Anlage weniger Strom bringt, als dein Auto maximal laden kann, geht auch einfach:

```
template:
  - sensor:
      - name: "Zendure Stromzähler"
        unique_id: "zendure_stromzaehler"
        device_class: power
        state_class: measurement
        unit_of_measurement: "W"
        state: >
          {% set sz = states('sensor.stromzaehler_leistung') | float(0) %}  # Stromzähler
          {% set wb = states('sensor.wallbox_leistung') | float(0) %}       # Wallbox

          {% if wb > 100 %}  # Auto lädt
            0
          {% else %}  # Auto lädt nicht
            {{ sz }}
          {% endif %}
```

Damit sollte dein Zendure nur Strom einspeisen, wenn das Auto nicht geladen wird.
Ein noch größerer PV Überschuss wird jedoch ignoriert und lädt den Zendure nicht.
